### ISSUE TITLE
Do not start if there is not enough disk space available of the file system

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/record-and-upload#18]
We need at least 1Gb to safely generate and upload the recording files. 
On start, we should perform an explicit check for the available disk space in the target recording directory and fail with a meaningful message if there is not enough space.

**Comment by neomatrix369** [comment]
Thinking of this, it is better to build this capability in the tdl-lord-of-runners as well, because its possible that the app might crash before it can check for diskspace and report it as an issue if you build it into the Java app.

Which the bash script might just survive and not load the Java app at all.

**Comment by neomatrix369** [comment]
We can also add a check inside the app, at two points, on at startup and another check regularly. In case, we run out of disk space say the client had 1.1GB and after a bit of coding, we won't have much space - I will create this PR later if you agree with me.

**Comment by julianghionoiu** [comment]
To keep it simple, the check should only be ran once, at startup and stop the recording if it fails.

The check should be done against the current volume, the volume that holds the ./record/localstore folder.
